### PR TITLE
BUGFIX: Fix realtime indexing of node deletion

### PR DESCRIPTION
**Pull request by kdambekalns**
See https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/issues/14 for details.

### CODE REVIEW

**Comment by kdambekalns** [comment]
See https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/issues/14#issuecomment-312013670 for the open issues with this approach…

**Comment by dfeyer** [comment]
So here we are, the fake node data are generated, currently the CLI build command is broken, but can be solved.

Not fully tested because midnight ... but at least my error log stay silent ;)

Now we need to decide what we do when the nodedata is not available in the IndexingJob, that can happens because of ordering, or during bulk indexing when the queue is huge. My current (post midnight) solution is to generate a RemovalJob for this missing NodeData so we are sure that it's removed from the index (better multiple removal, than no removal)

**Comment by dfeyer** [comment]
Test and review highly welcome

**Comment by peterbucher** [comment]
Hi @dfeyer - i want to test this PR and have a question regarding a change from @kdambekalns.
I suspect the following line, to ignore removed Nodes, as they are not found with the NodeRepository and therefore would not be instances of "NodeData". What do you think?

Did you check, debug.... this?

-> https://github.com/kdambekalns/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/blob/e3195b0e512938c08d706854978f4eccba6ce91a/Classes/IndexingJob.php#L33

**Comment by kdambekalns** [comment]
@peterbucher Yes, the `RemovalJob` is unaffected by those lines. IMO they are still useful as a safeguard in the `IndexingJob`, though.

**Comment by kdambekalns** [comment]
@peterbucher The `RemovalJob` also still has this check… It does no harm, but I'm not sure it would ever be needed (since the `NodeDataRepository` should return only `NodeData` instances.

@dfeyer did you check that?

**Comment by peterbucher** [comment]
@kdambekalns NodeDataRepository can return NULL, which is not a instance of NodeData. So i think this check does matter.

It seems to be better now in case of stability (background process) @dfeyer but, as far as i can see, the nodes (elements) and pages are not removed in the index. If i change some text within a text element, its updated. If i remove it, it will no longer be found, but it is still in the full text field of the corresponding page  node. But if i delete a page, its still in the index, but the Search result page does not display it, as there are no corresponding nodes in the database.

This leads to a wrong result which e.g. with Flowpack.SearchPlugin tells me, there is 1 Result found, but no result is displayed.

**Comment by kdambekalns** [comment]
I did some cleanup in the codebase and will push a follow-up. I'll try to test this and see if I can confirm what @peterbucher observed, as well.

**Comment by dfeyer** [comment]
> This leads to a wrong result which e.g. with Flowpack.SearchPlugin tells me, there is 1 Result found, but no result is displayed.

Need more debugging, will not have time this week to test this more. Hope @kdambekalns founds something, if not I try to work on it next week.

**Comment by peterbucher** [comment]
What's the current status, @kdambekalns ?

**Comment by kdambekalns** [comment]
Ok, (content and document) node removal seems to still be handled by `IndexingJob`, not `RemovalJob`. That leads to `action=indexing step=failed node=… message="Node data could not be loaded"` and thus the index is not updated correctly. I'll dig further…

**Comment by kdambekalns** [comment]
The cause is the way signals and slots are wired. When a node is removed, the `NodeIndexingManager` is tasked with `removeNode()`, that's fine. But during publishing, only the `afterNodePublishing` signal is emitted, wired to `indexNode()`. So the removal is not "seen" by the indexing code.

**Comment by kdambekalns** [comment]
When adding code to divert removals from within `indexNode()´ to `removeNode()`, the log shows removal operations being done. The fulltext is not updated correctly, though. The log shows `No fulltext root found for node …` entries.

So right now I assume the "fake nodes" we build do not return their parent on `getParent()` and thus the update fails…

**Comment by kdambekalns** [comment]
It might be that there is something else going wrong as well. When content node is removed, the log shows `Could not index node with identifier …, not found in workspace live` and when publishing the same identifier appears in `Removed node … from index.` But the related fulltext (root) is not updated…

**Comment by dfeyer** [comment]
Discussed to topic yesterday with @kdambekalns has we fake the node, this node does not have any parent ;) so we need to fake a bit more to have the full text index rebuild correctly.

**Comment by kdambekalns** [comment]
Ok. Removing a deleted node from the user workspace is handled correctly, it's just the removal from live during publishing that fails.

One thing that I fixed already: the target workspace was not passed through as needed. The data passed throuhg the queue looks good now.

The fulltext updates stil do not work, I pinpointed this down into the Groovy scripting so far…

**Comment by kdambekalns** [comment]
Fixed, cleaning up for commit. 🎉

**Comment by kdambekalns** [comment]
The collected results from this one:

- three new commits to this one
- https://github.com/neos/typo3cr-search/pull/26
- https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/239

**Comment by kdambekalns** [comment]
And some more, merged to resolve conflict and tweaked batch size default handling.

Note: for me, during local testing, the batch size of 500 broke indexing… but since it's configurable now, that can be solved if needed.

**Comment by kdambekalns** [comment]
Hey @dfeyer – it would be great if you could check this out!

**Comment by kdambekalns** [comment]
Found the batch size indexing issue (had to create https://github.com/neos/flow-development-collection/issues/1180 for this)… the message exceeds the shell argument list size limit with a batch size of 500. It works with 250. YMMV.

**Comment by fnkr** [comment]
@kdambekalns I think you accidentally referenced the wrong issue. You propably meant to reference https://github.com/neos/flow-development-collection/issues/1181, not 1180.

**Comment by kdambekalns** [comment]
@fnkr Yup, thanks! Fixed the comment…

**Comment by peterbucher** [comment]
@dfeyer @kdambekalns For me, this is working now! I tested to add / remove text within a textelement, as well as i deleted whole pages.

Great work! Waiting for the PR to be merged.

**Comment by dfeyer** [comment]
Thanks a lots @kdambekalns for this one

I merge it and will release a new version

**Comment by kdambekalns** [comment]
@dfeyer Awesome. Just to make sure, this needs neos/typo3cr-search#26 - did you check that as well?

**Pull request merged**
